### PR TITLE
Creating a README

### PR DESCRIPTION
**Pull request by Rishabh001pawar**
#23 
closes:- #23

### CODE REVIEW

**Comment by Rishabh001pawar** [comment]
i am GSSOC contributor ,please label it as GSSOC
Thank you

**Review by Kunal-agrawall — APPROVED** [review]
Good Job

**Review by Kunal-agrawall — APPROVED** [review]
Good

**Review by Kunal-agrawall — COMMENTED** [review]
Good job

**Comment by Rishabh001pawar** [comment]
assign me ,label it as gssoc

**Pull request merged**
